#端口号
server:
  port: 9999
#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zxk??useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: springboot02
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
